# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"convert_smiles": "MolClearner.ipynb",
         "mol_to_inchi": "MolClearner.ipynb",
         "build_inchi_dict": "MolClearner.ipynb",
         "find_inchikey_duplicates": "MolClearner.ipynb",
         "add_nitrogen_charges": "MolClearner.ipynb",
         "getlargestfragment": "MolClearner.ipynb",
         "remove_unwanted": "MolClearner.ipynb",
         "get_mixture": "MolClearner.ipynb",
         "normalize_mol": "MolClearner.ipynb",
         "get_stereo_info": "MolClearner.ipynb",
         "remove_racemic": "MolClearner.ipynb",
         "process_duplicates": "MolClearner.ipynb",
         "MolCleaner": "MolClearner.ipynb",
         "TARGET2TYPE": "MolGraphDataset.ipynb",
         "TYPE2TARGET": "MolGraphDataset.ipynb",
         "CHIRAL_DICT": "MolGraphDataset.ipynb",
         "HYBRIDIZATION": "MolGraphDataset.ipynb",
         "EDGE_FEATURES": "MolGraphDataset.ipynb",
         "ELEMENTS": "MolGraphDataset.ipynb",
         "encode_onehot": "MolGraphDataset.ipynb",
         "AtomFeaturizer": "MolGraphDataset.ipynb",
         "BondFeaturizer": "MolGraphDataset.ipynb",
         "MolecularGraph": "MolGraphDataset.ipynb",
         "MolecularDataset": "MolGraphDataset.ipynb",
         "save_df": "MolGraphDataset.ipynb",
         "MolecularGraphDataset": "MolGraphDataset.ipynb",
         "molgraph_collate_fn": "MolGraphDataset.ipynb",
         "MolGraphDataLoader": "MolGraphDataset.ipynb",
         "MessageGCN": "model.ipynb",
         "UpdateGCN": "model.ipynb",
         "GCNMPNmodel": "model.ipynb"}

modules = ["utils/sanitizer.py",
           "molgraphdataset.py",
           "models/gcnn.py"]

doc_url = "https://marcossantanaioc.github.io/molgraph/"

git_url = "https://github.com/marcossantanaioc/molgraph/tree/master/"

def custom_doc_links(name): return None
